# Generated by Django 5.2.3 on 2025-07-03 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_parent_post_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='session_key',
            field=models.CharField(blank=True, help_text='Session key for anonymous users', max_length=40, null=True),
        ),
    ]
